server {
    listen 80;
    server_name ismsota.lewi.nl;
    ##root /var/www/ismsota/current/public;
    root /home/leo/claude/isms/ota/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php;

    charset utf-8;

    # Block access to sensitive file extensions
	location ~* \.(log|json|lock|sql|bak|ini|env)$ {
		deny all;
		return 404;
	}


    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.4-fpm-ota-isms.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        
        # Ensure HTTPS is forwarded from HAProxy SSL termination
        set $my_https "";
        if ($http_x_forwarded_proto = "https") {
            set $my_https "on";
        }
        fastcgi_param HTTPS $my_https;

        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
